### ISSUE TITLE
Import error when starting my app with pg-boss 12.x

### ISSUE THREAD

**Issue by scesbron** [timgit/pg-boss#645]
I have an app based on solidstart that works well with pg-boss 11.1.2.

I tried to update it to version 12.x but when I start my app I have an import error:

```
ERROR  Cannot find module '/home/sebastien/dev/solid-pgboss/.output/server/node_modules/pg-boss/dist/node_modules/serialize-error/index.mjs' imported from /home/sebastien/dev/solid-pgboss/.output/server/node_modules/pg-boss/dist/src/manager.mjs                                                       12:20:19

    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1169:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:540:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:509:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:96:40)
    at link (node:internal/modules/esm/module_job:95:36) 

```

Here is a simple project that reproduces the error: https://github.com/scesbron/solid-pgboss

**Comment by timgit** [comment]
I've not tested with this tech stack before, which I'm assuming is the root cause.  I cloned your code but I was not able to get as far as the error you included.  It does match [this issue](https://github.com/nksaraf/vinxi/issues/177) in the vinxi repo, however.  Let me know what you find out.

**Comment by scesbron** [comment]
On my side I did not find out the root cause of this problem. I reverted my upgrade to stay with pg-boss 11.x

Solidstart is currently working on getting rid of vinxi so I may wait for a version without vinxi and try again to see if the problem is gone.

**Comment by timgit** [comment]
Out of curiosity, can you try with 12.2.0 instead of 12.3.0?  All deps were included in a bundle file in that release.  I changed this in 12.3.0 to evaluate a more simple dist format.

**Comment by scesbron** [comment]
On my test app it works well with version 12.2.0 instead of 12.3.0 so I think it is the new bundle that does not work correctly with vinxi.

**Comment by timgit** [comment]
I just pushed 12.3.1 to switch back to full bundling mode in tsdown.  There's a [solidjs compat page on tsdown](https://tsdown.dev/recipes/solid-support) but I didn't go down that rabbit hole. :)
